# Generated by Django 3.2.5 on 2021-10-12 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividadescristianas',
            fields=[
                ('activcris_id', models.AutoField(primary_key=True, serialize=False)),
                ('activcris_nombre', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Actividades Cristianas',
                'verbose_name_plural': 'Actividades Cristianas',
                'db_table': 'actividadescristianas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('benef_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('benef_nombres', models.CharField(max_length=200)),
                ('benef_apellidos', models.CharField(max_length=200)),
                ('benef_nombrepref', models.CharField(max_length=200)),
                ('benef_fechanac', models.DateField()),
                ('benef_edad', models.PositiveIntegerField(db_column='benef_edad', verbose_name='Edad')),
                ('benef_huerfano', models.BooleanField()),
                ('benef_nav', models.BooleanField()),
                ('benef_barrio', models.CharField(blank=True, max_length=200, null=True)),
                ('benef_direccion', models.CharField(max_length=200)),
                ('benef_telefono', models.BigIntegerField(blank=True, null=True)),
                ('benef_correo', models.CharField(max_length=120)),
                ('benef_img', models.ImageField(default='null', upload_to='plantillas')),
                ('benef_created', models.DateTimeField(auto_now_add=True)),
                ('benef_updated', models.DateTimeField(auto_now_add=True)),
                ('benef_activcrist', models.ForeignKey(db_column='benef_activcrist', on_delete=django.db.models.deletion.DO_NOTHING, to='plantillas.actividadescristianas')),
            ],
            options={
                'verbose_name': 'Beneficiario',
                'verbose_name_plural': 'Beneficiarios',
                'db_table': 'beneficiario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ciudades',
            fields=[
                ('ciu_id', models.AutoField(primary_key=True, serialize=False)),
                ('ciu_nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
                'db_table': 'ciudades',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Deberes',
            fields=[
                ('deb_id', models.AutoField(primary_key=True, serialize=False)),
                ('deb_nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Deber',
                'verbose_name_plural': 'Deberes',
                'db_table': 'deberes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('dep_id', models.AutoField(primary_key=True, serialize=False)),
                ('dep_nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'db_table': 'departamento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Discapacidadesfisicas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disfisica_nombre', models.CharField(max_length=100)),
                ('disfisica_descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Discapacidad física',
                'verbose_name_plural': 'Discapacidades físicas',
                'db_table': 'discapacidadesfisicas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Discapacidadesmentales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dismental_nombre', models.CharField(max_length=100)),
                ('dismental_descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Discapacidad mental',
                'verbose_name_plural': 'Discapacidades mentales',
                'db_table': 'discapacidadesmentales',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Educacionformal',
            fields=[
                ('eformal_id', models.IntegerField(primary_key=True, serialize=False)),
                ('eformal_nombre', models.CharField(max_length=100)),
                ('eformal_descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Educación Formal',
                'verbose_name_plural': 'Educación Formal',
                'db_table': 'educacionformal',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Enfermedadcronica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enfcronica_nombre', models.CharField(max_length=100)),
                ('enfcronica_descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Enfermedad crónica',
                'verbose_name_plural': 'Enfermedades crónicas',
                'db_table': 'enfermedadcronica',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Grupoetareo',
            fields=[
                ('grupeta_id', models.IntegerField(primary_key=True, serialize=False)),
                ('grupeta_nombre', models.CharField(max_length=100)),
                ('grupeta_descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'GrupoEtareo',
                'verbose_name_plural': 'GruposEtareos',
                'db_table': 'grupoetareo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Hobbies',
            fields=[
                ('hob_id', models.AutoField(primary_key=True, serialize=False)),
                ('hob_nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Hobbie',
                'verbose_name_plural': 'Hobbies',
                'db_table': 'hobbies',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Materias',
            fields=[
                ('mat_id', models.AutoField(primary_key=True, serialize=False)),
                ('mat_nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'db_table': 'materias',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('rel_id', models.AutoField(primary_key=True, serialize=False)),
                ('rel_nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Religion',
                'verbose_name_plural': 'Religiones',
                'db_table': 'religion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Rendimientoacademico',
            fields=[
                ('rendiaca_id', models.AutoField(primary_key=True, serialize=False)),
                ('rendiaca_nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Rendimiento Academico',
                'verbose_name_plural': 'Rendimientos Academicos',
                'db_table': 'rendimientoacademico',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('sex_id', models.AutoField(primary_key=True, serialize=False)),
                ('sex_nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Sexo',
                'verbose_name_plural': 'Sexos',
                'db_table': 'sexo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Historiaclinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('histclinica_peso', models.FloatField(blank=True, null=True)),
                ('histclinica_talla', models.FloatField(blank=True, null=True)),
                ('histclinica_tratmedico', models.TextField(blank=True, db_column='histclinica_tratMedico', null=True)),
                ('histclinica_created', models.DateTimeField(auto_now_add=True)),
                ('histclinica_updated', models.DateTimeField(auto_now_add=True)),
                ('histclinica_beneid', models.ForeignKey(blank=True, db_column='histclinica_beneid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='plantillas.beneficiario')),
                ('histclinica_disfisica', models.ManyToManyField(to='plantillas.Discapacidadesfisicas')),
                ('histclinica_dismental', models.ManyToManyField(to='plantillas.Discapacidadesmentales')),
                ('histclinica_enfcronica', models.ManyToManyField(to='plantillas.Enfermedadcronica')),
            ],
            options={
                'verbose_name': 'Historia Clínica',
                'verbose_name_plural': 'Historias Clínicas',
                'db_table': 'historiaclinica',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='benef_ciudad',
            field=models.ForeignKey(db_column='benef_ciudad', on_delete=django.db.models.deletion.DO_NOTHING, to='plantillas.ciudades'),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='benef_deberes',
            field=models.ManyToManyField(to='plantillas.Deberes'),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='benef_departamento',
            field=models.ForeignKey(db_column='benef_departamento', on_delete=django.db.models.deletion.DO_NOTHING, to='plantillas.departamento'),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='benef_eduformal',
            field=models.ForeignKey(db_column='benef_eduformal', on_delete=django.db.models.deletion.DO_NOTHING, to='plantillas.educacionformal'),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='benef_grupoeta',
            field=models.ForeignKey(db_column='benef_grupoeta', on_delete=django.db.models.deletion.DO_NOTHING, to='plantillas.grupoetareo'),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='benef_hobbies',
            field=models.ManyToManyField(to='plantillas.Hobbies'),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='benef_materias',
            field=models.ManyToManyField(to='plantillas.Materias'),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='benef_religion',
            field=models.ForeignKey(db_column='benef_religion', on_delete=django.db.models.deletion.DO_NOTHING, to='plantillas.religion'),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='benef_rendiaca',
            field=models.ForeignKey(db_column='benef_rendiaca', on_delete=django.db.models.deletion.DO_NOTHING, to='plantillas.rendimientoacademico'),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='benef_sexo',
            field=models.ForeignKey(db_column='benef_sexo', on_delete=django.db.models.deletion.DO_NOTHING, to='plantillas.sexo'),
        ),
    ]
