# Generated by Django 3.2.5 on 2021-08-15 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividadescristianas',
            fields=[
                ('activcris_id', models.AutoField(primary_key=True, serialize=False)),
                ('activcris_nombre', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Actividades Cristianas',
                'verbose_name_plural': 'Actividades Cristianas',
                'db_table': 'actividadescristianas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('benef_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('benef_nombres', models.CharField(max_length=200)),
                ('benef_apellidos', models.CharField(max_length=200)),
                ('benef_nombrepref', models.CharField(max_length=200)),
                ('benef_fechanac', models.DateField()),
                ('benef_huerfano', models.IntegerField()),
                ('benef_nav', models.IntegerField()),
                ('benef_barrio', models.CharField(blank=True, max_length=200, null=True)),
                ('benef_direccion', models.CharField(max_length=200)),
                ('benef_telefono', models.BigIntegerField(blank=True, null=True)),
                ('benef_correo', models.CharField(max_length=120)),
                ('benef_created', models.DateTimeField(auto_now_add=True)),
                ('benef_updated', models.DateTimeField(auto_now_add=True)),
                ('benef_activcrist', models.ForeignKey(db_column='benef_activcrist', on_delete=django.db.models.deletion.DO_NOTHING, to='plantillas.actividadescristianas')),
            ],
            options={
                'verbose_name': 'Beneficiario',
                'verbose_name_plural': 'Beneficiarios',
                'db_table': 'beneficiario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ciudades',
            fields=[
                ('ciu_id', models.AutoField(primary_key=True, serialize=False)),
                ('ciu_nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ciudades',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Deberes',
            fields=[
                ('deb_id', models.AutoField(primary_key=True, serialize=False)),
                ('deb_nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'deberes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('dep_id', models.AutoField(primary_key=True, serialize=False)),
                ('dep_nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'departamento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Educacionformal',
            fields=[
                ('eformal_id', models.IntegerField(primary_key=True, serialize=False)),
                ('eformal_nombre', models.CharField(max_length=100)),
                ('eformal_descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'educacionformal',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Grupoetareo',
            fields=[
                ('grupeta_id', models.IntegerField(primary_key=True, serialize=False)),
                ('grupeta_nombre', models.CharField(max_length=100)),
                ('grupeta_descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'grupoetareo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Hobbies',
            fields=[
                ('hob_id', models.AutoField(primary_key=True, serialize=False)),
                ('hob_nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'hobbies',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Materias',
            fields=[
                ('mat_id', models.AutoField(primary_key=True, serialize=False)),
                ('mat_nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'materias',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('rel_id', models.AutoField(primary_key=True, serialize=False)),
                ('rel_nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'religion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Rendimientoacademico',
            fields=[
                ('rendiaca_id', models.AutoField(primary_key=True, serialize=False)),
                ('rendiaca_nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'rendimientoacademico',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('sex_id', models.AutoField(primary_key=True, serialize=False)),
                ('sex_nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sexo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Materiasxbenef',
            fields=[
                ('matxben_id', models.IntegerField(primary_key=True, serialize=False)),
                ('matxben_idben', models.ForeignKey(blank=True, db_column='matxben_idben', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='plantillas.beneficiario')),
                ('matxben_idmat', models.ForeignKey(blank=True, db_column='matxben_idmat', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='plantillas.materias')),
            ],
            options={
                'db_table': 'materiasxbenef',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Hobbiesxbenef',
            fields=[
                ('hobxben_id', models.IntegerField(primary_key=True, serialize=False)),
                ('hobxben_idben', models.ForeignKey(blank=True, db_column='hobxben_idben', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='plantillas.beneficiario')),
                ('hobxben_idhob', models.ForeignKey(blank=True, db_column='hobxben_idhob', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='plantillas.hobbies')),
            ],
            options={
                'db_table': 'hobbiesxbenef',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Deberesxbenef',
            fields=[
                ('debxben_id', models.IntegerField(primary_key=True, serialize=False)),
                ('debxben_idben', models.ForeignKey(blank=True, db_column='debxben_idben', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='plantillas.beneficiario')),
                ('debxben_iddeb', models.ForeignKey(blank=True, db_column='debxben_iddeb', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='plantillas.deberes')),
            ],
            options={
                'db_table': 'deberesxbenef',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='benef_ciudad',
            field=models.ForeignKey(db_column='benef_ciudad', on_delete=django.db.models.deletion.DO_NOTHING, to='plantillas.ciudades'),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='benef_departamento',
            field=models.ForeignKey(db_column='benef_departamento', on_delete=django.db.models.deletion.DO_NOTHING, to='plantillas.departamento'),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='benef_eduformal',
            field=models.ForeignKey(db_column='benef_eduformal', on_delete=django.db.models.deletion.DO_NOTHING, to='plantillas.educacionformal'),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='benef_grupoeta',
            field=models.ForeignKey(db_column='benef_grupoeta', on_delete=django.db.models.deletion.DO_NOTHING, to='plantillas.grupoetareo'),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='benef_religion',
            field=models.ForeignKey(db_column='benef_religion', on_delete=django.db.models.deletion.DO_NOTHING, to='plantillas.religion'),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='benef_rendiaca',
            field=models.ForeignKey(db_column='benef_rendiaca', on_delete=django.db.models.deletion.DO_NOTHING, to='plantillas.rendimientoacademico'),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='benef_sexo',
            field=models.ForeignKey(db_column='benef_sexo', on_delete=django.db.models.deletion.DO_NOTHING, to='plantillas.sexo'),
        ),
    ]
