# Generated by Django 3.2.5 on 2021-08-15 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantillas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ciudades',
            options={'managed': True, 'verbose_name': 'Ciudad', 'verbose_name_plural': 'Ciudades'},
        ),
        migrations.AlterModelOptions(
            name='deberes',
            options={'managed': True, 'verbose_name': 'Deber', 'verbose_name_plural': 'Deberes'},
        ),
        migrations.AlterModelOptions(
            name='deberesxbenef',
            options={'managed': True, 'verbose_name': 'DeberxBenef', 'verbose_name_plural': 'DeberesxBenef'},
        ),
        migrations.AlterModelOptions(
            name='departamento',
            options={'managed': True, 'verbose_name': 'Departamento', 'verbose_name_plural': 'Departamentos'},
        ),
        migrations.AlterModelOptions(
            name='educacionformal',
            options={'managed': True, 'verbose_name': 'Educación Formal', 'verbose_name_plural': 'Educación Formal'},
        ),
        migrations.AlterModelOptions(
            name='grupoetareo',
            options={'managed': True, 'verbose_name': 'GrupoEtareo', 'verbose_name_plural': 'GruposEtareos'},
        ),
        migrations.AlterModelOptions(
            name='hobbies',
            options={'managed': True, 'verbose_name': 'Hobbie', 'verbose_name_plural': 'Hobbies'},
        ),
        migrations.AlterModelOptions(
            name='hobbiesxbenef',
            options={'managed': True, 'verbose_name': 'HobbiexBenef', 'verbose_name_plural': 'HobbiesxBenef'},
        ),
        migrations.AlterModelOptions(
            name='materias',
            options={'managed': True, 'verbose_name': 'Materia', 'verbose_name_plural': 'Materias'},
        ),
        migrations.AlterModelOptions(
            name='materiasxbenef',
            options={'managed': True, 'verbose_name': 'MateriaxBenef', 'verbose_name_plural': 'MateriasxBenef'},
        ),
        migrations.AlterModelOptions(
            name='religion',
            options={'managed': True, 'verbose_name': 'Religion', 'verbose_name_plural': 'Religiones'},
        ),
        migrations.AlterModelOptions(
            name='rendimientoacademico',
            options={'managed': True, 'verbose_name': 'Rendimiento Academico', 'verbose_name_plural': 'Rendimientos Academicos'},
        ),
        migrations.AlterModelOptions(
            name='sexo',
            options={'managed': True, 'verbose_name': 'Sexo', 'verbose_name_plural': 'Sexos'},
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='benef_img',
            field=models.ImageField(default='null', upload_to='plantillas'),
        ),
    ]
