# Generated by Django 3.2.5 on 2021-08-15 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plantillas', '0003_auto_20210815_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiario',
            name='benef_grupoeta',
            field=models.ForeignKey(db_column='benef_grupoeta', on_delete=django.db.models.deletion.DO_NOTHING, to='plantillas.grupoetareo'),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='benef_rendiaca',
            field=models.ForeignKey(db_column='benef_rendiaca', on_delete=django.db.models.deletion.DO_NOTHING, to='plantillas.rendimientoacademico'),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='benef_sexo',
            field=models.ForeignKey(db_column='benef_sexo', on_delete=django.db.models.deletion.DO_NOTHING, to='plantillas.sexo'),
        ),
    ]
