# Generated by Django 3.2.5 on 2021-08-27 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantillas', '0004_auto_20210815_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiario',
            name='benef_huerfano',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='benef_nav',
            field=models.BooleanField(),
        ),
    ]
