# Generated by Django 3.2.5 on 2021-08-28 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantillas', '0005_auto_20210827_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiario',
            name='benef_hobbies',
            field=models.ManyToManyField(to='plantillas.Hobbies'),
        ),
        migrations.DeleteModel(
            name='Hobbiesxbenef',
        ),
    ]
