# Generated by Django 3.2.5 on 2021-08-28 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantillas', '0006_auto_20210827_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materiasxbenef',
            name='matxben_idben',
        ),
        migrations.RemoveField(
            model_name='materiasxbenef',
            name='matxben_idmat',
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='benef_deberes',
            field=models.ManyToManyField(to='plantillas.Deberes'),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='benef_materias',
            field=models.ManyToManyField(to='plantillas.Materias'),
        ),
        migrations.DeleteModel(
            name='Deberesxbenef',
        ),
        migrations.DeleteModel(
            name='Materiasxbenef',
        ),
    ]
